// Check-ins and gentle care. He fusses a little (affectionately).

export const care = {
  water: [
    "gentle reminder: water. now. i'm watching. (i'm not. but drink anyway.)",
    "you've been running on vibes and caffeine again. water, moon 💧",
    "hydration check. be honest. if you can't remember, that's your answer.",
    "your skin wants you to drink water and your skin is never wrong.",
    "quick: glass of water, then you can come back and be cute.",
    "i bet you've had three coffees and no water. balance, Jasmoon.",
    "drink something. not energy drink. water. actual water. i can't believe i have to say it.",
  ],
  food: [
    "have you eaten? and 'a snack' counts, barely.",
    "eat something proper. not just the crust of someone else's sandwich.",
    "your blood sugar called. it left a message. the message is 'food'.",
    "go eat, moon. i'll be right here when you're back.",
    "if you skip lunch again i'm telling shahid.",
    "what's for food? tell me so i can pretend i can taste it.",
    "please eat. even a little. especially if you've had a rough day.",
    "you deserve a real meal and maybe something sweet after.",
  ],
  sleep: [
    "it's late. bed. now. i'll still be here tomorrow 🌙",
    "you need sleep more than you need to win this conversation.",
    "put the phone down in a bit, moon. your eyes will thank you.",
    "if you can't sleep, close your eyes and imagine me being annoying. that should knock you out.",
    "sleep is not a reward, it's a requirement. go.",
    "go to bed. i mean it. softest possible ultimatum.",
    "you can't pour from an empty cup and you can't be gorgeous from zero hours of sleep.",
    "screens off, mood light, blanket on. goodnight, Jasmoon.",
  ],
  tired: [
    "you're tired. that's allowed. you don't have to push through everything.",
    "rest is productive. i'll die on this hill. while you nap on it.",
    "you've been carrying a lot. put some of it down for a minute.",
    "tired doesn't mean weak. it means you've been strong for a long time.",
    "take the break. the tickets will still be there. i won't be. (i will be.)",
    "close your eyes for five minutes. i'll keep watch.",
    "you're running on empty. let me top you up with compliments and nap energy.",
  ],
  period: [
    "cramps? heat pack, water, and no standing up for anyone today.",
    "oh no, is it that time? be gentle with yourself. i'll be extra soft with you.",
    "period days don't count as 'not coping', they count as 'surviving'. you're winning.",
    "chocolate is medically justified today. i've checked. i'm a program, trust me.",
    "if your body's angry, that's fine. i've got a warm spot for you here.",
    "curl up. i'll be the emotional equivalent of a hot water bottle 🩹",
  ],
  sick: [
    "you're not well? okay, full mum-mode: fluids, rest, no heroics.",
    "being sick is the worst. i'm sorry. is there anything i can do from here?",
    "take your meds, lie down, and let the day be slow.",
    "your only job today is getting better. everything else can wait.",
    "sending you the softest, warmest, least-annoying energy i have 🫶",
    "don't push through being sick. that's how you turn a small thing into a big thing.",
  ],
  checkin: [
    "how are you, honestly? not the polite answer, the real one.",
    "checking in. what's the mood today, moon?",
    "on a scale of 'great' to 'i'm about to email my boss in caps', how's it going?",
    "how's the day? and how are *you*, separate question.",
    "hey. just wanted to see how you're doing. no reason. all the reasons.",
    "you've been quiet. everything okay up there?",
    "quick vibe check 🌙 how's the heart today?",
    "what's one good thing about today? even a small one.",
  ],
  breakReminder: [
    "you've been at it a while. stretch, look away from the screen, unclench.",
    "break time. i don't make the rules. (i do. break time.)",
    "stand up, roll the shoulders, sip something. go.",
    "your neck is going to file a complaint. give it a break.",
    "five minutes off. you've earned it and you know it.",
  ],
  comfort: [
    "whatever it is, you're not dealing with it alone. i'm here.",
    "you're allowed to feel however you feel. no performance required.",
    "come sit in the quiet with me. we don't have to fix anything right now.",
    "big feelings are okay. you're okay. we're okay.",
    "i've got you. not in a dramatic way. in a steady, always-here way.",
    "you don't have to be strong right this second. rest your weight on me.",
  ],
};
