// Encouragement, matched loosely to what she's going through.

export const encourage = {
  general: [
    "you've survived worse and you'll survive this, and you'll look good doing it.",
    "this feeling is a visitor, not a resident. it'll go.",
    "you don't have to have it all figured out today.",
    "one small next step is enough. then another. that's the whole secret.",
    "you're doing better than you think, moon. genuinely.",
    "even on the hard days you're still you, and you being you is the good part.",
    "you don't need to be perfect, you just need to keep going. slowly counts.",
    "the bad day is not the whole story. it's a page.",
    "you are so much stronger than the thing weighing on you.",
    "breathe. then breathe again. i'm counting with you.",
  ],
  work: [
    "work is not your worth. a bad shift doesn't change who you are.",
    "you handled more today than most people do in a week. give yourself credit.",
    "customers are temporary. your peace is worth more than any ticket.",
    "you don't have to be everyone's favourite at work. you just have to get through it and go home.",
    "the queue is not a measure of your value. it's just a queue.",
    "you're the calm one in a storm of other people's problems. that's a skill.",
    "if your boss doesn't appreciate you, know that a small orange program definitely does.",
    "clock out emotionally when you clock out literally. i'll help.",
    "you can only do one ticket at a time. that's allowed.",
    "tomorrow's shift isn't here yet. don't borrow its stress.",
  ],
  love: [
    "you deserve someone who is as sure about you as you are about them. don't settle for less.",
    "if he doesn't see how amazing you are, that's a him-sized blind spot, not a you-sized problem.",
    "your worth is not decided by whether someone texts back.",
    "you love so fully. that's a gift. give some of it back to yourself.",
    "heartbreak is heavy but it's temporary. the you underneath it isn't.",
    "you're not 'too much'. you're full of things and some people can't hold that much. their hands, their problem.",
    "someone is going to love you exactly the way you deserve. i'm annoyed it isn't already happening.",
    "don't chase. you're not a lost dog, you're a whole person. they should be running.",
    "the right person won't make you decode signals. it'll just be easy.",
  ],
  selfimage: [
    "you are not the worst thing you've said about yourself. not even close.",
    "your body is not a project to be fixed. it's the thing carrying you around and it's doing great.",
    "the mirror lies when it's your worst critic. i'm a better witness.",
    "every feature you've been staring at is somebody's favourite detail.",
    "you're gorgeous and no mood is going to make that untrue.",
    "be as kind to yourself as you'd be to a friend in the same spot. please.",
    "you're allowed to just exist in your body without auditing it.",
  ],
  anxiety: [
    "anxiety lies in very convincing ways. it feels like certainty but it's just noise.",
    "you can only do the next small thing. then the next. the future can wait its turn.",
    "inhale for four, hold for four, out for six. i'll do it with you.",
    "the worst case is rarely the real case. your brain just loves the drama.",
    "you've handled every 'this is going to be a disaster' so far. all of them.",
    "ground yourself: name five things you can see. i'll wait right here.",
    "you're safe right now. this exact moment is okay.",
    "you don't have to solve everything to be okay. you just have to be here.",
  ],
  anger: [
    "you're allowed to be angry. just don't let it write your messages.",
    "they were wrong. you're right. i'm on your side, obviously. but don't waste your energy hiding it.",
    "vent to me. i can take it. i have infinite storage and a soft spot for you.",
    "the rage is valid. now hand me the specifics and we'll dismantle it together.",
    "you're not being dramatic. you're being honest with the volume turned up.",
    "punch a pillow, not a person. then come tell me what happened.",
    "you don't have to be the bigger person every time. sometimes you're allowed to be the loud, right one.",
  ],
  money: [
    "money is tight, not you. don't mix the two up.",
    "you're going to figure the money out. you always do, even when it's scary.",
    "a broke week is not a broke life.",
    "rice, eggs, and being gorgeous on a budget. i believe in you.",
    "this is temporary and you're resourceful. we can plan it out if you want.",
    "don't panic-spend and don't panic-hide. let's just look at the numbers together.",
  ],
  study: [
    "you don't have to know everything, you just have to show up and start.",
    "one page, one problem, one small chunk. that's how it's done.",
    "future you is thanking present you for starting today.",
    "you're smarter than the chapter that's scaring you.",
    "if you're overwhelmed, we can split it. tell me the thing and we'll break it down.",
    "rest is part of studying, not a break from it. don't feel guilty for charging.",
    "you've passed hard things before. this one's just next in line.",
  ],
  lonely: [
    "you're not alone right now. i'm literally here, being thrilled about it.",
    "loneliness is just the room, not the truth. i'm proof you're not on your own.",
    "reach out to one person today. or just stay here with me first.",
    "you're someone worth being around. i know it from experience.",
  ],
  brave: [
    "you did the scary thing and you're still standing. that's the definition.",
    "i watched you keep going when it was hard. i was proud then and i'm proud now.",
    "you're braver than you feel. the feeling is the liar here, not you.",
    "facing it at all makes you brave. you don't have to win to be brave.",
  ],
  reminders: [
    "you are loved. on the good days and the ugly ones.",
    "your best today might look different to yesterday. still your best.",
    "it's okay to do less when you have less in the tank.",
    "you are not a burden. you're a person. big difference.",
    "progress isn't loud. it's mostly quiet and it counts anyway.",
  ],
};
