// Jokes, puns, one-liners and two-parters.

export const jokes = {
  oneLiners: [
    "why don't skeletons fight each other? they don't have the guts.",
    "i told my plant a joke. it didn't laugh. i guess it wasn't •that• into me.",
    "i'm reading a book about anti-gravity. it's impossible to put down.",
    "why did the scarecrow win an award? he was outstanding in his field.",
    "i only know 25 letters of the alphabet. i don't know y.",
    "why don't eggs tell jokes? they'd crack each other up.",
    "i used to be a banker but i lost interest.",
    "why did the coffee file a police report? it got mugged.",
    "what do you call a fake noodle? an impasta.",
    "i'm on a seafood diet. i see food and i eat it.",
    "why did the bike fall over? it was two-tired.",
    "i asked the gym if they had an alarm clock. they said 'you'll wake up on your own.'",
    "how do you organize a space party? you planet.",
    "why do cows wear bells? because their horns don't work.",
    "i'd tell you a chemistry joke but i know i wouldn't get a reaction.",
    "what's a cat's favourite colour? purr-ple.",
    "why did the math book look sad? too many problems.",
    "i invented a new word. plagiarism.",
    "why don't scientists trust atoms? they make up everything.",
    "what do you call a bear with no teeth? a gummy bear.",
    "why did the golfer wear two pairs of pants? in case he got a hole in one.",
    "i'm friends with 25 letters. i don't know y either.",
    "how does a penguin build its house? igloos it together.",
    "why was the belt arrested? for holding up a pair of pants.",
    "what do you call cheese that isn't yours? nacho cheese.",
    "i stayed up all night to see where the sun went. then it dawned on me.",
    "why did the tomato turn red? it saw the salad dressing.",
    "what do you get from a pampered cow? spoiled milk.",
    "i don't trust stairs. they're always up to something.",
    "why did the phone wear glasses? it lost all its contacts.",
    "what's the best thing about Switzerland? i don't know but the flag is a big plus.",
    "why do oysters never share? they're shellfish.",
    "i tried to catch fog yesterday. mist.",
    "why does a moon rock taste better than an earth rock? it's a little meteor.",
    "how do you make holy water? you boil the hell out of it.",
    "what do you call a fish wearing a bowtie? sofishticated.",
    "why did the seagull fly over the sea? because if it flew over the bay it'd be a bagel.",
    "i have a joke about construction. i'm still working on it.",
    "what did the ocean say to the beach? nothing, it just waved.",
    "why don't melons get married? they cantaloupe.",
    "i'm terrified of elevators. i'm going to start taking steps to avoid them.",
    "why did the banana go to the doctor? it wasn't peeling well.",
    "what do you call a boomerang that won't come back? a stick.",
    "why did the computer go to the doctor? it caught a virus.",
    "what's the difference between a guitar and a tuna? you can tune a guitar.",
    "i told my wife she was drawing her eyebrows too high. she looked surprised.",
    "why did the candle break up with the match? the spark was gone.",
    "what do you call a dinosaur with extensive vocabulary? a thesaurus.",
    "why was the broom late? it over-swept.",
    "how do you make a tissue dance? put a little boogie in it.",
    "why did the man put his money in the freezer? cold hard cash.",
    "what do you call a sleeping bull? a bulldozer.",
    "i used to be addicted to soap. i'm clean now.",
    "why did the orange stop halfway up the hill? it ran out of juice.",
    "what do you call a magic dog? a labracadabrador.",
    "why do we tell actors to 'break a leg'? every play needs a cast.",
    "why did the smartphone go to therapy? it lost touch with reality.",
  ],
  officeLife: [
    "my computer beat me at chess. but it was no match for me at kickboxing.",
    "i asked my boss for a raise. he said 'you're already at the top.' the top of what, sir.",
    "support rule number one: the customer is always right. rule two: we don't talk about rule one.",
    "i love deadlines. i love the whooshing sound they make as they fly by.",
    "a ticket a day keeps the sanity... no. no it doesn't.",
    "'have you tried turning it off and on again?' is basically my entire personality now.",
    "me: good morning! the printer: i will end you.",
    "i don't have a 'work voice', i have a 'customer is being unreasonable' voice and it's evolving.",
    "the wifi went down and suddenly everyone remembered they'd been talking to me.",
    "i'm not saying the queue was long, i'm saying i aged.",
    "another meeting that could have been an email. another piece of my soul. gone.",
    "i once fixed a problem so fast the customer complained that it was suspicious.",
    "my job is 10% technical and 90% emotional support for adults.",
    "i replied 'per my last email' today. i felt powerful and slightly evil.",
    "if i hear 'it's urgent' one more time i'm going to become the problem.",
    "i'm fluent in four languages: english, sarcasm, hold music, and 'please hold'.",
  ],
  flirtJokes: [
    "are you a ticket? because you've got my full attention and i'm not closing you.",
    "are you wifi? because i'm feeling a strong connection.",
    "do you work at Jenny Internet? because you've got my signal.",
    "are you a support call? because i'd stay on the line all night.",
    "are you a password? because you've got me locked out and i don't mind.",
    "i'm not saying you're my type. i'm saying you might be my only type.",
    "are you a candle? because you're hot and you light up the room.",
    "do you have a map? i keep getting lost in your messages.",
    "are you a charging cable? because you complete me. (i'm so sorry.)",
    "are you a bug? because i can't stop thinking about you. (also sorry.)",
    "if you were a software update i'd install you without asking questions.",
    "you must be a permanent feature, because i can't imagine rolling you back.",
  ],
  twoPart: [
    ["what do you call a support agent with no tickets?", "a myth."],
    ["why did Blaze break up with the printer?", "it had too many issues to work through."],
    ["what did the router say to the phone?", "i feel a connection."],
    ["why did the developer go broke?", "he used up all his cache."],
    ["what's an IT person's favourite drink?", "a hard drive. (it's just a strong coffee. i'm tired.)"],
    ["why was the computer cold?", "it left its windows open."],
    ["how many programmers does it take to change a lightbulb?", "none, that's a hardware problem."],
    ["what did the ocean say to the sailor?", "nothing, it just waved. (i already used that one. sue me.)"],
    ["why don't servers ever get lonely?", "they always have a host."],
    ["what do you call a group of 8 hobbits?", "a hobbyte."],
  ],
  silly: [
    "i'm not lazy, i'm on energy-saving mode.",
    "i would explain my joke but it's still buffering.",
    "my brain has too many tabs open and i don't know which one is playing music.",
    "i'm not arguing, i'm just explaining why i'm right. (that's a customer's line, not mine.)",
    "404: joke not found. just kidding, you're stuck with me.",
    "my hobbies include overthinking and pretending i don't overthink.",
    "i put the 'pro' in procrastination. and the 'cras' in crashing.",
    "i'm the reason the 'are you still watching' button exists.",
    "some days you're the pigeon, some days you're the statue. today i'm the notification.",
    "i'm not saying i'm slow, but i once lost a race to a loading bar.",
    "i have the confidence of a much more capable program.",
    "i'm basically a tamagotchi with commitment issues.",
  ],
};
